### PR TITLE
Fixes issue description and octokit pagination

### LINKED ISSUE #27: Project links and manifest versions are undefined in generated issue description
Version: 2.1.2

Both the link to a Snyk project and the "manifest version" are undefined in GitHub issue description. This is likely due to migrating from the deprecated Snyk v1 projects API to the new Snyk REST projects API.

Example:
```
Snyk project(s):
 * [`elastic/kibana(main):package.json`](undefined) (manifest version undefined)
```
 
 Expected:
```
Snyk project(s):
 * [`elastic/kibana(main):package.json`](https://app.snyk.io/org/kibana/project/a5b45d12-e2ba-4663-a7ef-acd7474ec295) (manifest version 8.12.0)
```

### LINKED ISSUE #29: Octokit API pagination results in invalid request headers in node >= 18
Version: 2.1.2

Due to some changes in [node 18]([https://nodejs.org/en/blog/announcements/v18-release-announce#fetch-experimental) - the introduction of a default global fetch API, one of the calls we make to `octokit.paginate` results in generating invalid request headers when runnign with node >= 18.
e.g.

> https://api.github.com/repos/elastic/security/labels?per_page=100&status=200&data=[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]%2C[object Object]"

As we use `octokit.paginate` successfully with a raw request URL elsewhere, the simplest solution is to replace the octokit API call within the paginate with the raw GitHub API URL.

From:

```
const responseData = await octokit.paginate(
    await client.issues.listLabelsForRepo({
      owner: ghOwner,
      repo: ghRepo,
      per_page: 100
    }),
    (response) => response.data
  )
```

To:
```
const responseData = await octokit.paginate(`GET /repos/${conf.ghOwner}/${conf.ghRepo}/labels?per_page=100`)
```

### PR DESCRIPTION
**Pull request by jeramysoucy**
Closes #27 
Closes #29 

## Summary 
This PR resolves the issue of undefined project links manifest version (see https://github.com/elastic/snyk-github-issue-creator/issues/27), as well as the issue where `octokit` pagination with API calls caused improper headers in low-level fetch in node >= 18 (see https://github.com/elastic/snyk-github-issue-creator/issues/29)

#### Undefined Values
The project links were derived from the response of the deprecated v1 all projects API - each project body contained a `browseUrl` property. According to the API migration documentation it:

> can be constructed using organization ID and project ID https://app.snyk.io/org/:orgId/project/:projectId

But this is inaccurate. The URL can be constructed from the organization name in lower-case and the project ID as such: `https://app.snyk.io/org/[org name]/project/[projectId]`

The manifest version used to be populated from the `imageTag` property return from the deprecated v1 all projects API. The API migration documentation claims that it:

> Can be fetched from the latest project snapshot via v1 POST org/:orgId/project/:projectId/history

But I found that this did not work. Example for several projects:

> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: 20.10.0-slim
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: 20.10.0-slim
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: nonroot
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined
> *** PROJECT IMAGE TAG: undefined 

Originally, I removed the `manifest version` from the output issue description, as it is not included in our other issue-generation automations. However, I found that I could still properly query for `imageTag` with the non-deprecated v1 single project API. As this API also returns the `browseUrl` property, it is not necessary to query for the organization name and manually construct the URL.

#### Fetch Header Issue
This PR fixes the fetch header issue by replacing the `octokit` API call within the `octokit` pagination call for querying issue labels with a raw request URL. This seems to resolve this issue and executes correctly in node 16, 18, and 20.

#### Additional
Lastly, error reporting around requests has been improved throughout the codebase. Previously, only low-level exceptions were being displayed if something went wrong, which did not include a path or reference back to which high-level operation caused the error. Error reports will now include a better description, along with a response status code and response details if available.

### CODE REVIEW

File: lib/snyk.js [hunk 1]
```diff
@@ -1,9 +1,10 @@
 'use strict'
 
 const request = require('request-promise-native')
+const { dressError } = require('./utils')
 
 const baseV1Url = 'https://snyk.io/api/v1'
-const baseRestUrl = 'https://api.snyk.io'
+const baseRestUrl = 'https://api.snyk.io/rest'
```
Comment (jeramysoucy) [inline lib/snyk.js:7]: I decided to include the full base here and just remove the '/rest' in the one place where it is redundant.

**Review by kc13greiner — APPROVED** [review]
Code Changes LGTM!

++ descriptive errors!

File: lib/snyk.js (hunk 1 above)
Comment (JacquiManzi) [reply lib/snyk.js:7]: @jeramysoucy I think this is now introducing this when used `Error: Failed to paginate request for get https://api.snyk.io/rest/rest/orgs/`, notice the double `/rest`

Comment (watson) [reply lib/snyk.js:7]: Related issue: https://github.com/elastic/snyk-github-issue-creator/issues/30
